apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "benchmark-subchart-level-2d.fullname" . }}
  labels:
    {{- include "benchmark-subchart-level-2d.labels" . | nindent 4 }}
data:
  name: {{ .Values.name }}