# SPDX-FileCopyrightText: 2024 Karl Theil @karlderkaefer
# SPDX-FileContributor: Karl Theil @karlderkaefer
#
# SPDX-License-Identifier: MIT-Modern-Variant

apiVersion: v2
name: umbrella
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: subchart-level-1
    repository: file://../subchart-level-1
    version: 0.1.0
