# SPDX-FileCopyrightText: 2024 Karl Theil @karlderkaefer
# SPDX-FileContributor: Karl Theil @karlderkaefer
#
# SPDX-License-Identifier: MIT-Modern-Variant

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "umbrella.fullname" . }}
  labels:
    {{- include "umbrella.labels" . | nindent 4 }}
data:
  name: {{ .Values.name }}