name: goreleaser

on:
  push:
    branches:
      - "main"
    tags:
      - "v*"
  pull_request:
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set up Go
        uses: actions/setup-go@v4
      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
            install-only: true
      - name: Show GoReleaser version
        run: goreleaser -v
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
            @semantic-release/exec
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
